"""
AWS Textract extraction: calls detect_document_text on page screenshots,
producing source="textract" DocumentStructure for side-by-side comparison with native PDF.

Requirements:
  - boto3 installed (pip install boto3)
  - AWS credentials in backend/.env:
      AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION (default: us-east-1)
      AWS_SESSION_TOKEN (optional, for temporary/federated credentials)
  - Page screenshots must already exist (generated by screenshot_service.py)

Note: detect_document_text accepts JPEG/PNG bytes up to 5 MB per page (synchronous).
For large pages, reduce SCREENSHOT_DPI in .env if images exceed the 5 MB limit.
"""
import logging
from pathlib import Path

from sqlalchemy.orm import Session

from app.models.document import Document
from app.models.extraction import Extraction
from app.models.audit import AuditLog
from app.config import get_settings
from app.schemas.structure import DocumentStructure, Chapter, ContentBlock, BoundingBox

logger = logging.getLogger(__name__)


def _get_textract_client():
    """Create a boto3 Textract client using credentials from settings."""
    import boto3
    settings = get_settings()
    kwargs: dict = {"region_name": settings.aws_region}
    if settings.aws_access_key_id:
        kwargs["aws_access_key_id"] = settings.aws_access_key_id
        kwargs["aws_secret_access_key"] = settings.aws_secret_access_key
    if settings.aws_session_token:
        kwargs["aws_session_token"] = settings.aws_session_token
    return boto3.client("textract", **kwargs)


def _textract_image_to_blocks(
    image_path: Path, document_id: str, page_num: int
) -> list[ContentBlock]:
    """Call AWS Textract detect_document_text on a page screenshot PNG.
    Returns a list of ContentBlock (one per LINE block), preserving bounding box geometry."""
    if not image_path.exists():
        logger.warning("Textract skipped page %s: image not found at %s", page_num, image_path)
        return []

    try:
        client = _get_textract_client()
        image_bytes = image_path.read_bytes()
        response = client.detect_document_text(Document={"Bytes": image_bytes})
    except Exception as e:
        logger.warning("Textract API call failed for page %s: %s", page_num, e)
        return []

    content_blocks: list[ContentBlock] = []
    block_index = 0
    for block in response.get("Blocks", []):
        if block.get("BlockType") != "LINE":
            continue
        text = (block.get("Text") or "").strip()
        if not text:
            continue

        # Textract geometry: normalised fractions (0-1) relative to page size
        bbox = None
        geo = block.get("Geometry", {}).get("BoundingBox")
        if geo:
            bbox = BoundingBox(
                left=geo.get("Left", 0.0),
                top=geo.get("Top", 0.0),
                width=geo.get("Width", 0.0),
                height=geo.get("Height", 0.0),
            )

        content_blocks.append(
            ContentBlock(
                id=f"{document_id}-p{page_num}-textract-b{block_index}",
                type="text",
                content=text,
                orderIndex=block_index,
                wordCount=len(text.split()),
                bbox=bbox,
            )
        )
        block_index += 1

    logger.info(
        "Textract page %s: extracted %d lines (confidence data preserved in bbox geometry)",
        page_num, len(content_blocks),
    )
    return content_blocks


def _get_page_count(db: Session, document_id: str) -> int:
    """Return page count stored on the Document row; falls back to 1."""
    doc = db.query(Document).filter(Document.id == document_id).first()
    if doc and doc.page_count:
        return doc.page_count
    return 1


def extract_textract(
    db: Session,
    document_id: str,
    file_path: str,
    doc_name: str,
    upload_path: Path | None = None,
) -> None:
    """Run AWS Textract detect_document_text on every page screenshot.
    Stores the result as source='textract' in the extractions table."""
    page_count = _get_page_count(db, document_id)
    screenshot_dir = (upload_path / document_id / "screenshots") if upload_path else None

    chapters: list[Chapter] = []
    total_word_count = 0

    for page_num in range(1, page_count + 1):
        content_blocks: list[ContentBlock] = []

        if screenshot_dir:
            screenshot_path = screenshot_dir / f"page_{page_num}.png"
            if screenshot_path.exists():
                content_blocks = _textract_image_to_blocks(screenshot_path, document_id, page_num)

        if not content_blocks:
            # Textract returned nothing (image missing, API error, or blank page)
            content_blocks = [
                ContentBlock(
                    id=f"{document_id}-textract-p{page_num}-b0",
                    type="text",
                    content="(no text extracted by Textract)",
                    orderIndex=0,
                    wordCount=0,
                )
            ]

        ch = Chapter(
            chapter_id=f"ch-p{page_num}",
            heading=f"Page {page_num}",
            content_blocks=content_blocks,
            order_index=page_num - 1,
            wordCount=sum(b.wordCount or 0 for b in content_blocks),
        )
        chapters.append(ch)
        total_word_count += ch.wordCount or 0

    structure = DocumentStructure(
        documentId=document_id,
        source="textract",
        chapters=chapters,
        totalWordCount=total_word_count,
        pageCount=page_count,
    )
    ext = Extraction(
        document_id=document_id,
        source="textract",
        structure=structure.model_dump(),
        parser_version=get_settings().parser_version,
    )
    db.add(ext)
    db.add(
        AuditLog(
            document_id=document_id,
            document_name=doc_name,
            reviewer="System",
            action="AWS Textract extraction completed",
            validation_result="Extracted",
            parser_version=get_settings().parser_version,
        )
    )
    db.commit()
    logger.info("Textract extraction stored for document %s (%d pages)", document_id, page_count)
